In [1]:
import sys
!{sys.executable} -m pip install tensorflow

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import csv
import nltk

In [3]:
df = pd.read_csv(r'C:\Users\i c\Desktop\final.csv')
df

Tweet  Keyword  pcl
0     Wasim bhai popular aur jhoote case uthane k sa...  mazdoor    1
1     Hahaha khob Mazaq ha jo yaha wazir a azam ka h...  mazdoor    0
2     chan sahb mazloom steel mill k mazdoor aap se ...  mazdoor    0
3     Kitny mazdoor reh huye thy unku list share kro...  mazdoor    0
4     Aaj mazdoor dey par UN mazdoro ko bhi hum yaad...  mazdoor    2
...                                                 ...      ...  ...
3379  Aur ek tumhara jija, jo saari zameen pe kabza ...   zameen    0
3380  How can you even compare a womans pain and a m...   zameen    0
3381  Ab to paani aakr sidha zameen pr rukta hai, mu...   zameen    0
3382             Jannat ka swad Zameen pe mil raha hai    zameen    0
3383  Tum haddi he halal krna tommy ab 40 din sa zad...   zameen    0

[3384 rows x 3 columns]

In [4]:
df.Tweet=df.Tweet.astype(str)

In [5]:
import matplotlib.pyplot as plt
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 

In [7]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score

def binary_scores(real, predictions):
    matrix = confusion_matrix(real, predictions)
    print("Accuracy ",accuracy_score(real, predictions))
    tn, fp, fn, tp = matrix.ravel()
    print("tn ", tn," fp ", fp , " fn ", fn, " tp ", tp)
    print("Precision ",precision_score(real, predictions, zero_division=1))
    print("Recall ",recall_score(real, predictions, zero_division=1))  
    print("F1 Score ",f1_score(real, predictions, zero_division=1))
    print('-' * 70)
    print()

def multi_scores(real, predictions):
    matrix = confusion_matrix(real, predictions)
    print("accuracy_score: ", accuracy_score(real, predictions))
    tn, fp, fn, tp = matrix.ravel()
    print("tn ", tn," fp ", fp , " fn ", fn, " tp ", tp)
    print("micro average scores:")
    print("precision_score: ", precision_score(real, predictions, average='micro', zero_division=1))
    print("recall_score: ", recall_score(real, predictions, average='micro'))
    print("f1_score: ", f1_score(real, predictions, average='micro'))
    print("macro average scores:")
    print("precision_score: ", precision_score(real, predictions, average='macro', zero_division=1))
    print("recall_score: ", recall_score(real, predictions, average='macro'))
    print("f1_score: ", f1_score(real, predictions, average='macro'))
    print('-' * 70)
    print()

In [8]:
def call_predictions(predictions_multi, y_test):
    prediction_list = []
    real_list = []
    print(predictions_multi, y_test)
    len(predictions_multi)
    len(y_test)
    for i in range(len(predictions_multi)):
        max = np.argmax(predictions_multi[i])
        prediction_list.append(max)
    predictions = np.array(prediction_list)

    for i in range(len(y_test)):
        max = np.argmax(y_test[i])
        real_list.append(max)
    real = np.array(real_list)
  
    return real, predictions

In [10]:
df.loc[df['pcl'] > 0, 'pcl'] = 1
df

Tweet  Keyword  pcl
0     Wasim bhai popular aur jhoote case uthane k sa...  mazdoor    1
1     Hahaha khob Mazaq ha jo yaha wazir a azam ka h...  mazdoor    0
2     chan sahb mazloom steel mill k mazdoor aap se ...  mazdoor    0
3     Kitny mazdoor reh huye thy unku list share kro...  mazdoor    0
4     Aaj mazdoor dey par UN mazdoro ko bhi hum yaad...  mazdoor    1
...                                                 ...      ...  ...
3379  Aur ek tumhara jija, jo saari zameen pe kabza ...   zameen    0
3380  How can you even compare a womans pain and a m...   zameen    0
3381  Ab to paani aakr sidha zameen pr rukta hai, mu...   zameen    0
3382             Jannat ka swad Zameen pe mil raha hai    zameen    0
3383  Tum haddi he halal krna tommy ab 40 din sa zad...   zameen    0

[3384 rows x 3 columns]

In [14]:
from sklearn.model_selection import train_test_split
import csv

In [15]:
training_X,testing_X, training_Y , testing_Y  = train_test_split(X,df['pcl'],random_state=42, test_size=0.2, stratify= df['pcl'])

In [23]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_res, y_res)
pred=clf.predict(testing_X)
testing_Y

915     0
2840    0
2025    0
1097    0
2031    0
       ..
1549    0
3335    0
1969    0
3127    0
813     1
Name: pcl, Length: 677, dtype: int64

In [24]:
matrix(testing_Y,pred)

Accuracy: 0.921713
F1 score: 0.545079
Precision: 0.795330
Recall: 0.534756
-------------------------
Accuracy :  92.17134416543574
F1 Score :  0.5450787975606355
Report : 
               precision    recall  f1-score   support

           0       0.92      1.00      0.96       622
           1       0.67      0.07      0.13        55

    accuracy                           0.92       677
   macro avg       0.80      0.53      0.55       677
weighted avg       0.90      0.92      0.89       677



In [25]:
from sklearn.linear_model import LogisticRegression
LR = LogisticRegression(random_state=0).fit(X_res, y_res)
pred1=LR.predict(testing_X)

In [26]:
matrix(testing_Y,pred1)

Accuracy: 0.905465
F1 score: 0.711731
Precision: 0.695106
Recall: 0.733090
-------------------------
Accuracy :  90.54652880354506
F1 Score :  0.7117308920587608
Report : 
               precision    recall  f1-score   support

           0       0.96      0.94      0.95       622
           1       0.43      0.53      0.48        55

    accuracy                           0.91       677
   macro avg       0.70      0.73      0.71       677
weighted avg       0.91      0.91      0.91       677



In [27]:
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(X_res.toarray(),y_res)
pred2 = NB.predict(testing_X.toarray())

In [28]:
matrix(testing_Y,pred2)

Accuracy: 0.828656
F1 score: 0.506461
Precision: 0.506800
Recall: 0.508974
-------------------------
Accuracy :  82.86558345642541
F1 Score :  0.5064605329311211
Report : 
               precision    recall  f1-score   support

           0       0.92      0.89      0.91       622
           1       0.09      0.13      0.11        55

    accuracy                           0.83       677
   macro avg       0.51      0.51      0.51       677
weighted avg       0.85      0.83      0.84       677



In [22]:
from imblearn.over_sampling import RandomOverSampler
from collections import Counter
over_sampler = RandomOverSampler(random_state=42)
X_res, y_res = over_sampler.fit_resample(training_X, training_Y )
print(f"Training target statistics: {Counter(y_res)}")
print(f"Testing target statistics: {Counter(testing_Y)}")

Training target statistics: Counter({0: 2488, 1: 2488})
Testing target statistics: Counter({0: 622, 1: 55})


In [13]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
t = Tokenizer(split = ' ', lower=True)
#Fit the Tokenizer on text
t.fit_on_texts(df['Tweet'].values)
#Converting text to sequences
X = t.texts_to_sequences(df['Tweet'].values)
#Padding the sequences
X = keras.preprocessing.sequence.pad_sequences(X)

In [14]:
from sklearn.model_selection import train_test_split
Y = pd.get_dummies(df['pcl']).values
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.25, random_state=42)

In [15]:
Y_train = np.asarray(y_train).astype('float32').reshape((-1,1))
Y_test = np.asarray(y_test).astype('float32').reshape((-1,1))

In [16]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import *

In [147]:
print(y_train.shape)
print(X_train.shape)

(2538, 2)
(2538, 66)


In [17]:
from keras.layers import *
def run_RNN(X_train, X_test, y_test, y_train, drop, no_of_layers, embedding_input_length, output_dimension ):
    model=keras.Sequential()
    model.add(Embedding(len(t.word_counts)+1, 128, input_length = embedding_input_length))
    if no_of_layers == 3:
        model.add(SimpleRNN(128, return_sequences=True))
        model.add(Dropout(drop))
    model.add(SimpleRNN(128, return_sequences=True))
    model.add(Dropout(drop))
    model.add(SimpleRNN(128))
    model.add(Dropout(drop))
    #model.add(Flatten())
    #model.add(GlobalAveragePooling2D())
    model.add(Dense(output_dimension, activation='sigmoid'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    batch_size = 32
    epochs = 2
    model.summary
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    predictions_double = model.predict(X_test)
    real, predictions = call_predictions(predictions_double,y_test)
    if output_dimension == 2:
        binary_scores(real, predictions)
    else:
        multi_scores(real, predictions)
   

In [1]:
run_RNN(X_train, X_test, y_test, y_train, 0.3, 2, X.shape[1], 2)

In [2]:
run_RNN(X_train, X_test, y_test, y_train, 0.7, 2, X.shape[1], 2)

In [4]:
run_RNN(X_train, X_test, y_test, y_train, 0.3, 3, X.shape[1], 2)

In [5]:
run_RNN(X_train, X_test, y_test, y_train, 0.7, 3, X.shape[1], 2)

In [164]:
def run_LSTM(X_train, X_test, y_test, y_train, drop, no_of_layers, embedding_input_length, output_dimension ):
    model=keras.Sequential()

    #embedding layer
    model.add(Embedding(len(t.word_counts)+1, 128, input_length = embedding_input_length))
    
    #lstm layers
    if no_of_layers == 3:
        model.add(LSTM(128, return_sequences=True))
        model.add(Dropout(drop))
    model.add(LSTM(128, return_sequences=True))
    model.add(Dropout(drop))
    model.add(LSTM(128))
    model.add(Dropout(drop))

    #Dense Layer
    model.add(Dense(output_dimension, activation='softmax'))

    #Adding loss function, optimizer, metrics
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    batch_size = 32
    epochs = 5

    # mc=ModelCheckpoint('best_model.h5', monitor='val_acc', mode='max', save_best_only=True,verbose=1)  


    #Training the Model
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    predictions_double = model.predict(X_test)
    real, predictions = call_predictions(predictions_double,y_test)
    if output_dimension == 2:
        binary_scores(real, predictions)
    else:
        multi_scores(real, predictions)

In [165]:
run_LSTM(X_train, X_test, y_test, y_train, 0.3, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 15s 127ms/step - loss: 0.2928 - accuracy: 0.9169
Epoch 2/5
80/80 [==============================] - 10s 128ms/step - loss: 0.1162 - accuracy: 0.9567
Epoch 3/5
80/80 [==============================] - 10s 129ms/step - loss: 0.0263 - accuracy: 0.9937
Epoch 4/5
80/80 [==============================] - 10s 126ms/step - loss: 0.0095 - accuracy: 0.9968
Epoch 5/5
27/27 [==============================] - 2s 40ms/step
[[9.9999905e-01 9.4039166e-07]
 [9.9999905e-01 9.4908961e-07]
 [1.0000000e+00 3.4620047e-08]
 ...
 [1.0000000e+00 4.8005891e-08]
 [9.9999917e-01 8.4361159e-07]
 [9.9865216e-01 1.3478730e-03]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8995271867612293
tn  746  fp  18  fn  67  tp  15
Precision  0.45454545454545453
Recall  0.18292682926829268
F1 Score  0.2608695652173913
----------------------------------------------------------------------



In [166]:
run_LSTM(X_train, X_test, y_test, y_train, 0.7, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 15s 126ms/step - loss: 0.3250 - accuracy: 0.9188
Epoch 2/5
80/80 [==============================] - 10s 128ms/step - loss: 0.2537 - accuracy: 0.9224
Epoch 3/5
80/80 [==============================] - 10s 128ms/step - loss: 0.0904 - accuracy: 0.9689
Epoch 4/5
80/80 [==============================] - 10s 128ms/step - loss: 0.0193 - accuracy: 0.9961
Epoch 5/5
27/27 [==============================] - 2s 40ms/step
[[9.9999940e-01 5.4646705e-07]
 [9.9999917e-01 7.8285387e-07]
 [9.9999988e-01 8.4669722e-08]
 ...
 [1.0000000e+00 5.5322250e-08]
 [9.9999976e-01 2.6836580e-07]
 [9.9995077e-01 4.9209320e-05]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.9066193853427896
tn  759  fp  5  fn  74  tp  8
Precision  0.6153846153846154
Recall  0.0975609756097561
F1 Score  0.16842105263157897
----------------------------------------------------------------------



In [167]:
run_LSTM(X_train, X_test, y_test, y_train, 0.3, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 22s 182ms/step - loss: 0.2620 - accuracy: 0.9212
Epoch 2/5
80/80 [==============================] - 15s 185ms/step - loss: 0.0815 - accuracy: 0.9716
Epoch 3/5
80/80 [==============================] - 15s 182ms/step - loss: 0.0210 - accuracy: 0.9941
Epoch 4/5
80/80 [==============================] - 15s 183ms/step - loss: 0.0036 - accuracy: 0.9992
Epoch 5/5
27/27 [==============================] - 3s 62ms/step
[[1.0000000e+00 3.5883023e-08]
 [1.0000000e+00 3.8261593e-08]
 [1.0000000e+00 1.4290824e-08]
 ...
 [1.0000000e+00 1.8215109e-08]
 [9.9999988e-01 1.3874958e-07]
 [9.9999940e-01 5.4615185e-07]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.9066193853427896
tn  748  fp  16  fn  63  tp  19
Precision  0.5428571428571428
Recall  0.23170731707317074
F1 Score  0.3247863247863248
----------------------------------------------------------------------



In [168]:
run_LSTM(X_train, X_test, y_test, y_train, 0.7, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 22s 182ms/step - loss: 0.2665 - accuracy: 0.9212
Epoch 2/5
80/80 [==============================] - 15s 182ms/step - loss: 0.0935 - accuracy: 0.9740
Epoch 3/5
80/80 [==============================] - 15s 185ms/step - loss: 0.0259 - accuracy: 0.9941
Epoch 4/5
80/80 [==============================] - 15s 181ms/step - loss: 0.0072 - accuracy: 0.9980
Epoch 5/5
27/27 [==============================] - 3s 64ms/step
[[1.0000000e+00 8.1370457e-09]
 [1.0000000e+00 3.0982818e-08]
 [1.0000000e+00 4.3812758e-09]
 ...
 [1.0000000e+00 5.6355818e-09]
 [1.0000000e+00 5.4429872e-08]
 [9.9999928e-01 7.4370769e-07]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8995271867612293
tn  745  fp  19  fn  66  tp  16
Precision  0.45714285714285713
Recall  0.1951219512195122
F1 Score  0.27350427350427353
----------------------------------------------------------------------



In [169]:
def run_GRU(X_train, X_test, y_test, y_train, drop, no_of_layers, embedding_input_length, output_dimension ):
    model=keras.Sequential()
    model.add(Embedding(len(t.word_counts)+1, 128, input_length = embedding_input_length))
    if no_of_layers == 3:
        model.add(GRU(128, return_sequences=True))
        model.add(Dropout(drop))
    model.add(GRU(128, return_sequences=True))
    model.add(Dropout(drop))
    model.add(GRU(128))
    model.add(Dropout(drop))
    model.add(Dense(output_dimension, activation='softmax'))
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    batch_size = 32
    epochs = 5
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    predictions_double = model.predict(X_test)
    real, predictions = call_predictions(predictions_double,y_test)
    if output_dimension == 2:
        binary_scores(real, predictions)
    else:
        multi_scores(real, predictions)

In [170]:
run_GRU(X_train, X_test, y_test, y_train, 0.3, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 15s 114ms/step - loss: 0.2724 - accuracy: 0.9200
Epoch 2/5
80/80 [==============================] - 10s 124ms/step - loss: 0.0729 - accuracy: 0.9748
Epoch 3/5
80/80 [==============================] - 10s 120ms/step - loss: 0.0134 - accuracy: 0.9953
Epoch 4/5
80/80 [==============================] - 9s 114ms/step - loss: 0.0031 - accuracy: 0.9988
Epoch 5/5
27/27 [==============================] - 2s 32ms/step
[[9.9999976e-01 2.8393669e-07]
 [9.9927622e-01 7.2378491e-04]
 [1.0000000e+00 6.5507075e-09]
 ...
 [1.0000000e+00 3.7473824e-09]
 [1.0000000e+00 4.2387118e-08]
 [9.0880579e-01 9.1194235e-02]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8877068557919622
tn  740  fp  24  fn  71  tp  11
Precision  0.3142857142857143
Recall  0.13414634146341464
F1 Score  0.18803418803418806
----------------------------------------------------------------------



In [171]:
run_GRU(X_train, X_test, y_test, y_train, 0.3, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 21s 165ms/step - loss: 0.2507 - accuracy: 0.9228
Epoch 2/5
80/80 [==============================] - 13s 165ms/step - loss: 0.0656 - accuracy: 0.9799
Epoch 3/5
80/80 [==============================] - 13s 164ms/step - loss: 0.0123 - accuracy: 0.9961
Epoch 4/5
80/80 [==============================] - 13s 161ms/step - loss: 0.0054 - accuracy: 0.9984
Epoch 5/5
27/27 [==============================] - 3s 49ms/step
[[9.9999976e-01 2.3404289e-07]
 [9.9999988e-01 7.7377855e-08]
 [1.0000000e+00 2.7631726e-09]
 ...
 [1.0000000e+00 3.0037466e-09]
 [1.0000000e+00 1.2801174e-08]
 [9.9908996e-01 9.1000495e-04]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8829787234042553
tn  736  fp  28  fn  71  tp  11
Precision  0.28205128205128205
Recall  0.13414634146341464
F1 Score  0.18181818181818182
----------------------------------------------------------------------



In [172]:
run_GRU(X_train, X_test, y_test, y_train, 0.7, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 14s 112ms/step - loss: 0.2743 - accuracy: 0.9180
Epoch 2/5
80/80 [==============================] - 9s 110ms/step - loss: 0.0758 - accuracy: 0.9764
Epoch 3/5
80/80 [==============================] - 9s 113ms/step - loss: 0.0157 - accuracy: 0.9961
Epoch 4/5
80/80 [==============================] - 9s 113ms/step - loss: 0.0056 - accuracy: 0.9992
Epoch 5/5
27/27 [==============================] - 2s 35ms/step
[[9.9999988e-01 7.6610696e-08]
 [9.9999213e-01 7.8567073e-06]
 [1.0000000e+00 1.7935916e-09]
 ...
 [1.0000000e+00 1.9587552e-09]
 [1.0000000e+00 4.2886579e-09]
 [9.9580956e-01 4.1904976e-03]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8877068557919622
tn  735  fp  29  fn  66  tp  16
Precision  0.35555555555555557
Recall  0.1951219512195122
F1 Score  0.25196850393700787
----------------------------------------------------------------------



In [173]:
run_GRU(X_train, X_test, y_test, y_train, 0.3, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 21s 165ms/step - loss: 0.2551 - accuracy: 0.9196
Epoch 2/5
80/80 [==============================] - 13s 161ms/step - loss: 0.0730 - accuracy: 0.9783
Epoch 3/5
80/80 [==============================] - 13s 166ms/step - loss: 0.0174 - accuracy: 0.9957
Epoch 4/5
80/80 [==============================] - 13s 161ms/step - loss: 0.0014 - accuracy: 1.0000
Epoch 5/5
27/27 [==============================] - 3s 48ms/step
[[1.0000000e+00 2.2953966e-08]
 [9.9999988e-01 1.3742020e-07]
 [1.0000000e+00 5.8312115e-09]
 ...
 [1.0000000e+00 6.5103749e-09]
 [1.0000000e+00 5.6128858e-08]
 [9.9508661e-01 4.9134428e-03]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8971631205673759
tn  743  fp  21  fn  66  tp  16
Precision  0.43243243243243246
Recall  0.1951219512195122
F1 Score  0.26890756302521013
----------------------------------------------------------------------



In [174]:
def run_biLSTM(X_train, X_test, y_test, y_train, drop, no_of_layers, embedding_input_length, output_dimension ):
    model=keras.Sequential()
    model.add(Embedding(len(t.word_counts)+1, 128, input_length = embedding_input_length))
    if no_of_layers == 3:
        model.add(Bidirectional(LSTM(128, return_sequences=True)))
        model.add(Dropout(drop))
    model.add(Bidirectional(LSTM(128, return_sequences=True)))
    model.add(Dropout(drop))
    model.add(Bidirectional(LSTM(128)))
    model.add(Dropout(drop))
    model.add(Dense(output_dimension, activation='softmax'))
    if output_dimension == 2:
        model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    else:
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    batch_size = 32
    epochs = 5
    # oh_y_train=tf.one_hot(y_train, output_dimension)
    model.fit(X_train, y_train, epochs=epochs, batch_size=batch_size)
    predictions_double = model.predict(X_test)
    real, predictions = call_predictions(predictions_double,y_test)
    if output_dimension == 2:
        binary_scores(real, predictions)
    else:
        multi_scores(real, predictions)

In [175]:
run_biLSTM(X_train, X_test, y_test, y_train, 0.3, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 28s 224ms/step - loss: 0.2589 - accuracy: 0.9192
Epoch 2/5
80/80 [==============================] - 18s 226ms/step - loss: 0.0840 - accuracy: 0.9724
Epoch 3/5
80/80 [==============================] - 18s 230ms/step - loss: 0.0174 - accuracy: 0.9968
Epoch 4/5
80/80 [==============================] - 18s 222ms/step - loss: 0.0048 - accuracy: 0.9996
Epoch 5/5
27/27 [==============================] - 4s 73ms/step
[[9.9999976e-01 2.6733866e-07]
 [9.9912292e-01 8.7707787e-04]
 [9.9999988e-01 1.5666589e-07]
 ...
 [9.9999964e-01 3.3601464e-07]
 [9.9999964e-01 3.3223492e-07]
 [5.3071408e-06 9.9999464e-01]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8877068557919622
tn  737  fp  27  fn  68  tp  14
Precision  0.34146341463414637
Recall  0.17073170731707318
F1 Score  0.22764227642276427
----------------------------------------------------------------------



In [176]:
run_biLSTM(X_train, X_test, y_test, y_train, 0.7, 2, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 27s 222ms/step - loss: 0.2443 - accuracy: 0.9180
Epoch 2/5
80/80 [==============================] - 18s 222ms/step - loss: 0.0875 - accuracy: 0.9649
Epoch 3/5
80/80 [==============================] - 18s 223ms/step - loss: 0.0223 - accuracy: 0.9949
Epoch 4/5
80/80 [==============================] - 18s 227ms/step - loss: 0.0058 - accuracy: 0.9988
Epoch 5/5
27/27 [==============================] - 4s 69ms/step
[[1.0000000e+00 5.9539534e-08]
 [9.9999988e-01 6.7455417e-08]
 [1.0000000e+00 1.1983872e-08]
 ...
 [1.0000000e+00 1.2484593e-08]
 [9.9999988e-01 6.2525203e-08]
 [7.2399814e-07 9.9999928e-01]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8971631205673759
tn  745  fp  19  fn  68  tp  14
Precision  0.42424242424242425
Recall  0.17073170731707318
F1 Score  0.24347826086956523
----------------------------------------------------------------------



In [177]:
run_biLSTM(X_train, X_test, y_test, y_train, 0.3, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 41s 342ms/step - loss: 0.2285 - accuracy: 0.9228
Epoch 2/5
80/80 [==============================] - 28s 353ms/step - loss: 0.0682 - accuracy: 0.9752
Epoch 3/5
80/80 [==============================] - 26s 330ms/step - loss: 0.0150 - accuracy: 0.9957
Epoch 4/5
80/80 [==============================] - 26s 329ms/step - loss: 0.0041 - accuracy: 0.9992
Epoch 5/5
27/27 [==============================] - 6s 104ms/step
[[9.9999976e-01 2.2958307e-07]
 [9.9999642e-01 3.5632561e-06]
 [1.0000000e+00 2.8672627e-08]
 ...
 [1.0000000e+00 2.6877039e-08]
 [9.9997807e-01 2.1888642e-05]
 [4.0815762e-06 9.9999595e-01]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.892434988179669
tn  738  fp  26  fn  65  tp  17
Precision  0.3953488372093023
Recall  0.2073170731707317
F1 Score  0.27199999999999996
----------------------------------------------------------------------



In [178]:
run_biLSTM(X_train, X_test, y_test, y_train, 0.7, 3, X.shape[1], 2)

Epoch 1/5
80/80 [==============================] - 40s 330ms/step - loss: 0.2774 - accuracy: 0.9188
Epoch 2/5
80/80 [==============================] - 26s 331ms/step - loss: 0.1124 - accuracy: 0.9677
Epoch 3/5
80/80 [==============================] - 26s 330ms/step - loss: 0.0416 - accuracy: 0.9886
Epoch 4/5
80/80 [==============================] - 27s 333ms/step - loss: 0.0130 - accuracy: 0.9972
Epoch 5/5
27/27 [==============================] - 6s 111ms/step
[[9.99999881e-01 1.05208684e-07]
 [9.99999881e-01 1.78257082e-07]
 [9.99999881e-01 6.30899137e-08]
 ...
 [1.00000000e+00 5.21648964e-08]
 [9.99999881e-01 1.14700008e-07]
 [3.59414667e-02 9.64058578e-01]] [[1 0]
 [1 0]
 [1 0]
 ...
 [1 0]
 [1 0]
 [0 1]]
Accuracy  0.8971631205673759
tn  747  fp  17  fn  70  tp  12
Precision  0.41379310344827586
Recall  0.14634146341463414
F1 Score  0.2162162162162162
----------------------------------------------------------------------



In [36]:
pip install tensorflow_hub

Note: you may need to restart the kernel to use updated packages.Requirement already satisfied: protobuf>=3.8.0 in c:\anaconda\lib\site-packages (from tensorflow_hub) (3.19.1)



In [37]:
import sys
!{sys.executable} -m pip install tensorflow_text

In [39]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [38]:
import tensorflow_hub as hub
import tensorflow_text as text

In [40]:
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

In [41]:
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

In [42]:
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [43]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 text (InputLayer)              [(None,)]            0           []                               
                                                                                                  
 keras_layer_2 (KerasLayer)     {'input_mask': (Non  0           ['text[0][0]']                   
                                e, 128),                                                          
                                 'input_type_ids':                                                
                                (None, 128),                                                      
                                 'input_word_ids':                                                
                                (None, 128)}                                                

In [44]:
METRICS = [
      tf.keras.metrics.BinaryAccuracy(name='accuracy'),
      tf.keras.metrics.Precision(name='precision'),
      tf.keras.metrics.Recall(name='recall')
]

model.compile(optimizer='adam',
 loss='binary_crossentropy',
 metrics=METRICS)

In [45]:
from sklearn.model_selection import train_test_split
x = df['Tweet']
y = df['pcl']
X_train, X_test, y_train, y_test = train_test_split(x, y, train_size = 0.8)

In [63]:
print(X_train.shape)
print(y_train.shape)

(2707,)
(2707,)


In [46]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
85/85 [==============================] - 882s 10s/step - loss: 0.3314 - accuracy: 0.8825 - precision: 0.0521 - recall: 0.0216
Epoch 2/5
85/85 [==============================] - 845s 10s/step - loss: 0.2779 - accuracy: 0.9139 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 3/5
85/85 [==============================] - 863s 10s/step - loss: 0.2678 - accuracy: 0.9132 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 4/5
85/85 [==============================] - 841s 10s/step - loss: 0.2618 - accuracy: 0.9128 - precision: 0.0000e+00 - recall: 0.0000e+00
Epoch 5/5
85/85 [==============================] - 844s 10s/step - loss: 0.2575 - accuracy: 0.9132 - precision: 0.2000 - recall: 0.0043


In [47]:
pred = model.predict(X_test)
pred = np.round(pred).astype(int)
from sklearn import metrics
acc_score = metrics.accuracy_score(y_test, pred)
precision = metrics.precision_score(y_test, pred,zero_division=1)
recall = metrics.recall_score(y_test, pred,zero_division=1)
f1_score = metrics.f1_score(y_test, pred, average='macro',zero_division=1)
print(acc_score)
print(precision)
print(recall)
print(f1_score)

22/22 [==============================] - 216s 10s/step
0.9364844903988183
0.3333333333333333
0.023809523809523808
0.5057974705033529
